name: final-project-env

dependencies:
  - pandas
  - pyarrow
  - python=3.8
  - pip
  - pyspark
  - pip: 
    - prefect
    - prefect-gcp[cloud_storage]
    - prefect_gcp[bigquery]
    - sodapy
    - google-cloud-dataproc




